config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 
  resources :users, only: [:index, :show] do
    resources :posts, only: [:new, :create, :index, :show, :destroy ] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end
  # get 'pages/blog'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    can :read, :all
    # Define User abilities

    if user.admin? :admin
      can :manage, :all
    else
      can :manage, Comment, user_id: user.id
      can :manage, Post, user_id: user.id
      can :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  def update_comment_counter
    post.increment!(:CommentsCounter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  # after_save :update_like_counter

  def update_like_counter
    post.increment!(:LikesCounter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :likes, foreign_key: :post_id
  has_many :comments, foreign_key: :post_id
  belongs_to :user
  validates :Title, presence: true, length: { in: 1..249 }
  validates :CommentsCounter, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :LikesCounter, presence: true, numericality: { greater_than_or_equal_to: 0 }
  after_save :update_user_counter
  def update_user_counter
    user.increment!(:PostsCounter)
  end

  def recent_commemnt
    comments.order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments, foreign_key: :user_id
  has_many :likes, foreign_key: :user_id
  has_many :posts, foreign_key: :user_id
  validates :Name, presence: true, length: { in: 1..255 }
  validates :email, presence: true
  validates :encrypted_password, presence: true
  validates :PostsCounter, presence: true, numericality: { greater_than_or_equal_to: 0 }

  def admin?(requested_role)
    role == requested_role.to_s
  end

  def recent_three_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:Name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:Name, :email, :password, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    respond_to do |format|
      format.html { render :new, locals: { comment: @comment } }
    end
  end

  def create
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @comment = @user.comments.new(handle_params)
    @comment.user_id = @user.id
    @comment.post_id = params[:post_id]
    if @comment.save
      flash[:success] = 'Succesfully created a comment'
      redirect_to user_post_path(@user.id, @post)
    else
      flash.new[:error] = 'encountered an error'
      render new, locals: { comment: @comment }
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @post = Post.find(params[:post_id])
    @post.CommentsCounter -= 1
    @comment.destroy!
    @post.save
    flash[:success] = 'successfuly deleted'
    redirect_to user_post_path(@post.user_id, @post.id)
  end

  def handle_params
    params.require(:my_comment).permit(:Text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @likes = Like.new(user_id: @user.id, post_id: params[:post_id])
    if @likes.save
      @post.increment!(:LikesCounter)
      redirect_to user_posts_path(@user, @post)
    else
      flash.now[:error] = 'comment not added'
      @likes.errors.full_messages.join(', ')
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def blog; end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  def new
    @post = Post.new
    respond_to do |format|
      format.html { render :new, locals: { post: @post } }
    end
  end

  def create
    current_user = User.find(params[:user_id])
    @post = Post.new(helper_params)
    @post.user_id = current_user.id
    @post.CommentsCounter = 0
    @post.LikesCounter = 0
    if @post.save
      flash[:success] = 'Added succesfully'
      redirect_to user_posts_path(current_user)
    else
      flash.now[:error] = 'question could not  be saved'
      render :new, locals: { post: @post }
    end
  end

  def show
    @user = User.find(params[:user_id])
    @posts = Post.where(user_id: @user.id)
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    user = User.find(params[:user_id])
    user.PostsCounter -= 1
    @post.destroy!
    user.save
    flash[:success] = 'You have deleted this post!'
    redirect_to user_posts_path(user.id)
  end

  private

  def helper_params
    params.require(:my_post).permit(:Title, :Text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = Post.where(user_id: @user.id)
  end

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/comments/_form.html.erb
<%= form_with model: @comment, url: user_post_comments_path, method: :post, local: true, scope: :my_comment do |f|%>
    <div>
      <%= f.label :Text%>
      <%= f.text_field :Text%>
    </div>
    <%= f.submit "Comment" %>
  <% end %>

app/views/comments/new.html.erb
<h2 id="new_h21">Comment Here</h2>
<div id="new_comments_form_cont">
  <%= render "form" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div>
      <% if user_signed_in?%>
      <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "my_button" %>
      <% else %>
      <div>
      </div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/pages/blog.html.erb
<h1>Pages#blog</h1>
<p>Find me in app/views/pages/blog.html.erb</p>

app/views/posts/_form.html.erb
<%= form_with model: @post, url: user_posts_path, method: :post, local: true, scope: :my_post do |f| %>
    <div>
      <%= f.label :Title %>
      <%= f.text_field :Title %>
    </div>
    <div>
      <%= f.label :Text %>
      <%= f.text_field :Text %>
    </div>
      <%= f.submit "Create Post" %>
  <% end %>

app/views/posts/index.html.erb
<div id="container_index_posts">
  <div id="container_container">
      <% if @user.Photo?%>
       <img id="container_container_img" src="<%= @user.Photo %>" alt="user profile">
      <% else %>
       <img id="container_container_img" src="https://img.freepik.com/free-photo/fun-backpacker-german-shepherd-dog-cartoon-character_183364-80975.jpg?size=338&ext=jpg&ga=GA1.2.1392401042.1675851204" alt="user profile">
      <%end%>
      <div id="container_container_div">
        <h3><%= @user.Name %></h3>
        <p>Number of posts: <%= @user.PostsCounter %></p>
        
      </div>
    </div>
    <% @posts[0...5].each do |post|%>
    <div id="show_container_user_id">
      <% if can? :destroy, post %>
        <%= button_to "Delete Post", user_post_path(@user.id, post.id), :method => :delete %>
      <% end %>
      <h3>Post #<%= post.id %> Title: <%= post.Title %></h3>
      <p><%= post.Text %></p>
      <h4>Comments <%= post.CommentsCounter %> likes: <%= post.LikesCounter %></h4>
      <%= form_with url: "/users/#{@user.id}/posts/#{post.id}/likes" do |f| %>
        <%= f.submit "like posts"%>
      <% end %>
    </div>
    <% @comments=Comment.where(post_id: post.id)%>
    <div id="container_index_posts_comments_container">
    <% @comments.each do |comment| %>
        <div id="container_index_posts_comments">
         <%= @user.Name%>: <%= comment.Text%>
        </div>
    <% end %>
    </div>
  <% end %>
  <div id="show_container_post_button_container">
    <button id="show_container_post_button">Pagination</button>
  </div>
</div>

app/views/posts/new.html.erb
<div id="new_post_form_cont">
  <%= render "form" %>
</div>

app/views/posts/show.html.erb
<div id="post_show_container">
  <div id="post_show_container_upper">
  <div id="post_show_container_header">
    <h3>Post #<%= @post.id%> by <%=@user.Name%> Title: <%= @post.Title%></h3>
    <h5>Comments:<%= @post.CommentsCounter%> Likes: <%=@post.LikesCounter%></h5>
  </div>
  <p><%= @post.Text %></p>
  </div>
  <% @comments=Comment.where(post_id:@post.id) %>
  <div id="container_index_posts_show_comments_container">
    <% @comments.each do |comment| %>
      <p><%=@user.Name%>: <%= comment.id %>  Comment: <%= comment.Text %></p>
      <% if can? :destroy, comment %> 
        <%= button_to "Delete comment", user_post_comment_path(@post.user_id, @post.id, comment.id), method: :delete, data: {confirm: "confirm to delete"} %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/_user.html.erb
    <div id="container_container">
     <% if user.Photo?%>
        <img id="container_container_img" src="<%= user.Photo %>" alt="user profile">
      <% else %>
        <img id="container_container_img" src="https://img.freepik.com/free-photo/fun-backpacker-german-shepherd-dog-cartoon-character_183364-80975.jpg?size=338&ext=jpg&ga=GA1.2.1392401042.1675851204" alt="user profile">
      <%end%>
      <div id="container_container_div">
        <h3><%= link_to user.Name, "/users/#{user.id}"%></h3>
        <p>Number of posts: <%= user.PostsCounter %></p>
      </div>
    </div>

app/views/users/index.html.erb
<div id="container"> 
  <%= render @users%>
</div>

app/views/users/show.html.erb
<div id="show_container_user">
  <%= render @user %>
  <div id="show_container_user_bio">
    <h4>Bio</h4>
    <p>
      Lorem ipsum dolor sit amet, 
      consectetur adipiscing elit, 
      sed do eiusmod tempor incididunt ut 
      labore et dolore magna aliqua. 
      Ut enim ad minim veniam, quis nostrud exercitation ullamco 
      laboris nisi ut aliquip ex ea commodo consequat.
    </p>
  </div>
  <% @user.recent_three_posts.each do |post|%>
    <div class='post' id="show_container_user_id">
      <h3> <%= link_to "Post: #{post.id} ", "/users/#{@user.id}/posts/#{post.id}" %></h3>
      <p><%= post.Text %></p>
      <h4>Comments <%= post.CommentsCounter %> likes: <%= post.LikesCounter %></h4>
    </div>
  <% end %>
  <div id="show_container_user_button_container">
    <button id="show_container_user_button"><%= link_to "See all posts", "/users/#{@user.id}/posts" %></button>
  </div>
</div>